/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Live */
    get: operations["live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Analyses */
    get: operations["list_analyses_v1_analyses_get"];
    put?: never;
    /** Create Analysis */
    post: operations["create_analysis_v1_analyses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/analyses/{analysis_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Analysis */
    get: operations["get_analysis_v1_analyses__analysis_id__get"];
    put?: never;
    post?: never;
    /** Delete Analysis */
    delete: operations["delete_analysis_v1_analyses__analysis_id__delete"];
    options?: never;
    head?: never;
    /** Update Analysis */
    patch: operations["update_analysis_v1_analyses__analysis_id__patch"];
    trace?: never;
  };
  "/v1/trials": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Trials */
    get: operations["search_trials_v1_trials_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/trials/{nct_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Trial */
    get: operations["get_trial_v1_trials__nct_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Analysis */
    Analysis: {
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** @default draft */
      status: components["schemas"]["AnalysisStatus"];
      /** Title */
      title: string;
      trial: components["schemas"]["TrialDraft"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at?: string;
    };
    /**
     * AnalysisStatus
     * @enum {string}
     */
    AnalysisStatus: "draft" | "ready";
    /** CreateAnalysisRequest */
    CreateAnalysisRequest: {
      /** Title */
      title?: string | null;
      trial: components["schemas"]["TrialDraft"];
    };
    /** Endpoint */
    Endpoint: {
      /** Description */
      description?: string | null;
      /** Measure */
      measure: string;
      /** Time Frame */
      time_frame?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Intervention */
    Intervention: {
      /** Description */
      description?: string | null;
      /** Intervention Type */
      intervention_type: string;
      /** Name */
      name: string;
    };
    /** Site */
    Site: {
      /** City */
      city?: string | null;
      /** Country */
      country: string;
      /** Facility */
      facility?: string | null;
      /** Latitude */
      latitude?: number | null;
      /** Longitude */
      longitude?: number | null;
      /** State */
      state?: string | null;
      /** Status */
      status?: string | null;
    };
    /** SourceReference */
    SourceReference: {
      /** Field Locators */
      field_locators?: {
        [key: string]: string;
      };
      /** Provider */
      provider: string;
      /** Record Id */
      record_id: string;
      /**
       * Retrieved At
       * Format: date-time
       */
      retrieved_at: string;
      /** Source Version */
      source_version?: string | null;
      /** Url */
      url: string;
    };
    /** StudyDesign */
    StudyDesign: {
      /** Allocation */
      allocation?: string | null;
      /**
       * Arm Count
       * @default 0
       */
      arm_count: number;
      /** Intervention Model */
      intervention_model?: string | null;
      /** Masking */
      masking?: string | null;
      /** Primary Purpose */
      primary_purpose?: string | null;
      /** Study Type */
      study_type: string;
    };
    /** TrialDraft */
    TrialDraft: {
      /** Biomarker */
      biomarker?: string | null;
      /** Conditions */
      conditions: string[];
      /** Eligibility Criteria */
      eligibility_criteria: string;
      /** Enrollment */
      enrollment: number;
      /** Enrollment Type */
      enrollment_type?: string | null;
      /** Healthy Volunteers */
      healthy_volunteers?: boolean | null;
      /** Indication */
      indication: string;
      /** Interventions */
      interventions: components["schemas"]["Intervention"][];
      /** Maximum Age */
      maximum_age?: string | null;
      /** Minimum Age */
      minimum_age?: string | null;
      /** Nct Id */
      nct_id: string;
      /** Overall Status */
      overall_status: string;
      /** Phases */
      phases: string[];
      /** Primary Completion Date */
      primary_completion_date?: string | null;
      /** Primary Endpoints */
      primary_endpoints: components["schemas"]["Endpoint"][];
      /** Secondary Endpoints */
      secondary_endpoints?: components["schemas"]["Endpoint"][];
      /** Sex */
      sex?: string | null;
      /** Sites */
      sites?: components["schemas"]["Site"][];
      source: components["schemas"]["SourceReference"];
      /** Start Date */
      start_date?: string | null;
      study_design: components["schemas"]["StudyDesign"];
      /** Summary */
      summary?: string | null;
      /** Title */
      title: string;
    };
    /** TrialSearchResponse */
    TrialSearchResponse: {
      /** Items */
      items: components["schemas"]["TrialSearchResult"][];
      /** Next Page Token */
      next_page_token?: string | null;
      /** Total Count */
      total_count?: number | null;
    };
    /** TrialSearchResult */
    TrialSearchResult: {
      /** Conditions */
      conditions: string[];
      /** Enrollment */
      enrollment?: number | null;
      /** Interventions */
      interventions: string[];
      /** Nct Id */
      nct_id: string;
      /** Overall Status */
      overall_status: string;
      /** Phases */
      phases: string[];
      /** Title */
      title: string;
      /**
       * Us Site Count
       * @default 0
       */
      us_site_count: number;
    };
    /** UpdateAnalysisRequest */
    UpdateAnalysisRequest: {
      /** Title */
      title?: string | null;
      trial?: components["schemas"]["TrialDraft"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_analyses_v1_analyses_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "x-demo-user-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Analysis"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_analysis_v1_analyses_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "x-demo-user-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Analysis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_analysis_v1_analyses__analysis_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "x-demo-user-id"?: string | null;
      };
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Analysis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_analysis_v1_analyses__analysis_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "x-demo-user-id"?: string | null;
      };
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_analysis_v1_analyses__analysis_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
        "x-demo-user-id"?: string | null;
      };
      path: {
        analysis_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Analysis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_trials_v1_trials_get: {
    parameters: {
      query: {
        query: string;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrialSearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_trial_v1_trials__nct_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nct_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TrialDraft"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
